# Site settings
author: Nick Lombardi
title: Web Development Through Flatiron School
header-img: img/home-bg.png
email: nelom3@gmail.com
copyright_name: Nick Lombardi
description: > # this means to ignore newlines until "baseurl:"
  Articles About Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nedlom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
