# Site settings
author: imperative-scientist-4600
title: 
header-img: img/home-bg.png
email: nelom3@gmail.com
copyright_name: imperative-scientist-4600
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nedlom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
